name: Auto Version Bump

on:
  push:
    branches:
      - main

jobs:
  version-bump:
    runs-on: ubuntu-latest
    # Nu rula dacă commit-ul e deja de la bot (evită loop infinit)
    if: github.actor != 'github-actions[bot]' && !contains(github.event.head_commit.message, '[skip-version]')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0
          
      - name: Bump version
        run: |
          # Citește versiunea curentă
          VERSION=$(cat VERSION)
          
          # Extrage major, minor, patch
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          
          # Incrementează patch
          PATCH=$((PATCH + 1))
          
          # Scrie noua versiune
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "$NEW_VERSION" > VERSION
          
          echo "Version bumped: $VERSION -> $NEW_VERSION"
          
      - name: Commit and push
        run: |
          git config user.name "Mateiasi1"
          git config user.email "dragosmateiasi@gmail.com"
          git add VERSION
          git diff --staged --quiet || git commit -m "🔖 Bump version to $(cat VERSION) [skip-version]"
          git push

